# very BIG NOTE that i need to put here
# this config will download everything inside a "userdata" folder
# "userdata" folder will have another folder called "models" and "ui"
# "models" will have your models downloaded to it
# "ui" will have some your webui element
# for "ui" it will be explained in the webui section
#
# if you don't understand how YAML BLOCK SEQUENCE work its recommended for you read some tutorial for it
#
# default template for most part
# - name: (file name.safetensors / file name.pt / file name.ckpt etc)
#   url: (file url)
#
# you can copy the template as many as you want for example
# - name: model1.safetensors
#   url: http://example.com/model1
# - name: model2.pt
#   url: http://example.com/model2
#
common:
  models:
    - name: AOM3_orangemixs.safetensors
      url: https://huggingface.co/WarriorMama777/OrangeMixs/resolve/main/Models/AbyssOrangeMix3/AOM3_orangemixs.safetensors
    - name: realcartoonAnime_v9.safetensors
      url: https://civitai.com/api/download/models/252727?type=Model&format=SafeTensor&size=pruned&fp=fp16
  vae:
    - name: vae-ft-mse-840000-ema-pruned.safetensors
      url: https://civitai.com/api/download/models/131654
    - name: kl-f8-anime2.safetensors
      url: https://civitai.com/api/download/models/131654
  lora:
    - name: add_detail.safetensors
      url: https://civitai.com/api/download/models/62833
  embeddings:
    # - name:
    #   url:
  hypernetwork:
    # - name:
    #   url:
  controlnet:
    - name: contolnet_sd15_openpose.pth
      url: https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_openpose.pth
    - name: contolnet_sd15_depth.pth
      url: https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_depth.pth
    - name: contolnet_sd15_canny.pth
      url: https://huggingface.co/lllyasviel/ControlNet/resolve/main/models/control_sd15_canny.pth
sd:
  # this is a section for stable diffusion webui
  # "ui" folder will have this structure
  #
  # ui
  # `-- sd
  #     |-- extensions
  #     |   `-- .
  #     |-- models
  #     |   `-- .
  #     |-- outputs
  #     |   `-- .
  #     |-- scripts
  #     |   `-- .
  #     |-- config.json
  #     `-- ui-config.json
  #
  # in case you want to add something to stable diffusion, e.g custom script
  # put it here
  #
  # for models folder, only download here if its not covered in common section
  # e.g sam model for segment anything extensions
  # ---------------------------------------
  #
  # extensions use git to download
  #
  # git template
  # - name: (folder name/repo name)
  #   url: (repo url)
  #   branch: (branch name OPTIONAL)
  #   commit: (commit hash OPTIONAL)
  #
  # example
  # - name: extension1
  #   url: https://example.com/gituser/extension1
  # - name: extension2
  #   url: https://example.com/gituser/extension2
  #   branch: dev
  #
  # branch and commit are optional
  # if not present then will download the latest commit on the main branch
  #
  # oh yea controlnet will be installed whether you want it or not (even if you don't include it)
  extensions:
    - name: adetailer
      url: https://github.com/Bing-su/adetailer
    - name: batchlinks-webui
      url: https://github.com/etherealxx/batchlinks-webui
    - name: multidiffusion-upscaler-for-automatic1111
      url: https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111
    - name: a1111-sd-webui-tagcomplete
      url: https://github.com/DominikDoom/a1111-sd-webui-tagcomplete
    - name: sd-webui-controlnet
      url: https://github.com/Mikubill/sd-webui-controlnet
    - name: sd-webui-infinite-image-browsing
      url: https://github.com/zanllp/sd-webui-infinite-image-browsing
    - name: sd-civitai-browser-plus
      url: https://github.com/BlafKing/sd-civitai-browser-plus.git
    - name: sd-dynamic-thresholding
      url: https://github.com/mcmonkeyprojects/sd-dynamic-thresholding.git
    - name: ultimate-upscale-for-automatic1111
      url: https://github.com/Coyote-A/ultimate-upscale-for-automatic1111
  #
  # custom_download same as name url format but with dir
  #
  # example
  # - dir: models/sam
  #   name: sam_model.pth
  #   url: https://example.com/sam_model.pth
  #
  # do remember, dir will always "ui" folder subdirectory
  # so, with the example above it will download to ui/sd/models/sam/sam_model.pth
  #
  # if you happen to put absolute / full path e.g /root/somedir, it will download to a warning folder in "ui" folder
  #
  # this is useful when you want to download extra models but its not covered in common section
  #
  custom_download:
    - dir: models/ESRGAN
      name: 4x-UltraSharp.pth
      url: https://mega.nz/folder/qZRBmaIY#nIG8KyWFcGNTuMX_XNbJ_g/file/vRYVhaDA
  #
  # if you want to use your pre-configured config.json or ui-config.json
  # you can put the json download url here
  #
  # by doing this, you can reduce the amount of time need to setup the webui to your liking
  #
  config_json: https://raw.githubusercontent.com/VeonN4/config/main/config.json
  ui_config_json:
  #
  # env stand for Environment
  # args stand for Arguments
  # both env and args are using this template
  # - (a text)
  #
  # for example
  # - EXAMPLE_ENV=examplevalue
  # - --example-arg examplevalue
  #
  # please see https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings
  # for more explain about what env and arg can be used
  #
  env:
    # - --EXAMPLE_ENV=examplevalue
  args:
    - --xformers --theme dark
